### ISSUE TITLE
RStudio crashing, .cpp issues in virtual environment?

### ISSUE THREAD

**Issue by kohlkopf** [nickjer/singularity-rstudio#6]
Receiving an error when running `ScaleData()` from R package Seurat, code available [here](https://github.com/satijalab/seurat/blob/65b77a9480281ef9ab1aa8816f7c781752092c18/R/preprocessing.R).

It ran the first time through, and now hangs without making any progress and eventually crashes RStudio. Wondering if this could have something to do with the way the compiler is set up in the image. If it's any hint running the same function of RStudio Cloud crashes the session as well. They are using Docker for virtualization.

`[rsession-kkinning] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563`

Thanks!

**Comment by nickjer** [comment]
RStudio Server doesn't always give the most helpful error messages. What happens when you run that function in an R console?

You can launch an R console using this Singularity image with the following command:

```console
$ singularity run --app R singularity-rstudio.simg
```

**Comment by kohlkopf** [comment]
Odd--it runs just fine. Maybe there is an issue with my session being stored? Something like the slot in the S4 object being half computed and loaded upon resuming the session, and conflict arising from trying to overwrite the slot? This seems like more of an RStudio server issue than an issue with your image.

**Comment by nickjer** [comment]
I've seen the `ERROR session hadabend` before in RStudio. Typically when you leave a session open and shutdown RStudio Server. You can delete your session data in your home directory to get rid of that message, or in the future logout before shutting down RStudio Server.

**Comment by kohlkopf** [comment]
Clearing the .rstudio folder seemed to do the trick. Thanks for your excellent work on this image!
