### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [nickjer/singularity-rstudio#7]
hey @nickjer ! I'm seeing you doing a lot of pulls for this container, and as a courtesy I want to remind you that the weekly allowance for (globally) all GET requests for this container is 100. So - you are advised to pull the container, and then use the binary pulled. if you continue exec/run you will use up your weekly allowance really quickly. More detail -> https://singularityhub.github.io/singularityhub-docs/2019/release-announcement/

**Comment by nickjer** [comment]
Hi @vsoch,

I never pulled this container down in a very long time (I just personally maintain this container for others). I do have Travis CI pull down the nickjer/singularity-r container as the base container to build and test this container. But it sounds like you are seeing a lot of activity around this container in particular.

If you have more details I may be able to look into it more. But as of right now, the only time I ever pull down any of my containers is through Travis CI, which doesn't happen too often at this time.

**Comment by vsoch** [comment]
hey @nickjer ! I think you are actually probably ok - I saw it pulled twice in unision yesterday and had remembered it from the day before (just once) so you have a whopping total of 3 (I just checked). I do think it's likely just your Travis pipelines, and they are well within reason! Apologies for jumping the gun, I'm keeping a very close watch to make sure everything is ok :) Closing!
